# The configuration in this file is the basic configuration and reflects the production systems as closely as possible.
version: "3.9"
services:
  landing:
    build:
      context: .
      dockerfile: landing.dockerfile
      target: production
    environment:
      PORT: 3001
      NEXT_PUBLIC_MATOMO_SITE_ID: "2"
      NEXT_PUBLIC_MATOMO_BASE_URL: https://t-vl-web.validity.io
      NEXT_PUBLIC_MATOMO_TRACKER_URL: https://analytics.validitylabs.org/matomo.php
      NEXT_PUBLIC_MATOMO_SRC_URL: https://analytics.validitylabs.org/matomo.js
    ports:
      - 3001:3001
